image: gitpod/workspace-full-vnc

tasks:
  - name: "Setup Environment"
    init: |
      # Install Docker and other dependencies
      apt-get update
      apt-get install -y wget git unzip docker.io zcat gunzip openjdk-11-jdk

      # Install Nextflow
      wget -qO- https://get.nextflow.io | bash
      mv nextflow /usr/local/bin/
      chmod +x /usr/local/bin/nextflow

      # Verify Nextflow installation
      nextflow -version

      # Pull Entap Docker image
      docker pull plantgenomics/entap:latest

      # Clone the workshop repository
      git clone https://github.com/cynthiawebster/bgaworkshop-2024.git

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
    visibility: public

workspaceLocation: "/workspace"
