image: gitpod/workspace-full-vnc

tasks:
  - name: "Setup Environment"
    init: |
      # Install Docker and other dependencies
      sudo apt-get update
      sudo apt-get install -y wget git unzip docker.io

      # Install Java (for Nextflow)
      sudo apt-get install -y openjdk-11-jdk

      # Install Nextflow
      wget -qO- https://get.nextflow.io | bash
      sudo mv nextflow /usr/local/bin/
      sudo chmod +x /usr/local/bin/nextflow

      # Verify Nextflow installation
      nextflow -version

      # Define the container names and versions
      containers=("agat:1.2.0--pl5321hdfd78af_0"
                  "viennarna:2.5.1--py39pl5321h2add14b_0"
                  "subread:2.0.6--he4a0461_0"
                  "bedtools:2.30.0--hc088bd4_0"
                  "seqkit:2.3.1--h9ee0642_0"
                  "eggnog-mapper:2.1.9--pyhdfd78af_0"
                  "busco:5.4.4--pyhdfd78af_0"
                  "seqtk:1.3--h7132678_4"
                  "sra-tools:3.0.5--h9f5acd7_1"
                  "fastp:0.23.2--hb7a2d85_2"
                  "miniprot:0.11--he4a0461_2"
                  "gmap:2021.08.25--pl5321h67092d7_2"
                  "hisat2:2.2.1--py38he1b5a44_0"
                  "samtools:1.17--hd87286a_1"
                  "stringtie:2.2.1--hecb563c_2"
                  "transdecoder:5.7.1--pl5321hdfd78af_0"
                  "vsearch:2.22.1--hf1761c0_0"
                  "gffread:0.12.7--hd03093a_1"
                  "gffcompare:0.12.6--h4ac6f70_2")

      # Loop through the containers and pull Docker images
      for container in "${containers[@]}"; do
          docker pull quay.io/biocontainers/${container}
      done

      containers=("sagnikbanerjee15/psiclass:1.0.3" 
                  "plantgenomics/easel:python"
                  "plantgenomics/easel:perl"
                  "plantgenomics/entap:latest"
                  "plantgenomics/easel:augustus")

      for container in "${containers[@]}"; do
          docker pull "${container}"
      done

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
    visibility: public

workspaceLocation: "/workspace"
